// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://jkblxwbhrppdkwowwzei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprYmx4d2JocnBwZGt3b3d3emVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDYzNjEsImV4cCI6MjA3MTE4MjM2MX0.flkJftrSDFmG_lnGPnvHDDFiZXSnVpsbbAcsE4suQY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});